### PR TITLE
#PRS-3209: Update menu expand/collapse

### PR DESCRIPTION
**Pull request by meyerhp**
### Description
Cleaned up the menu logic in the theme, see [176](https://github.com/SPANDigital/presidium-theme-website/pull/176). This PR updates scroll spy to work with the new nav.

### Issue
https://spandigital.atlassian.net/browse/PRSDM-3209

### Checklist before merging

* [x] Is this code covered by tests?
* [x] Is the documentation updated for this change?

### CODE REVIEW

**Review by christopherbrunsdon — APPROVED** [review]
Tested .. OK

**Review by effleurager — CHANGES_REQUESTED** [review]
Breaks nesting activation. How'd you test this @christopherbrunsdon?
Uploading Screen Recording 2023-01-11 at 12.42.08.mov…

**Comment by meyerhp** [comment]
> Breaks nesting activation. How'd you test this @christopherbrunsdon?
> 
>  Screen.Recording.2023-01-11.at.12.42.08.mov

You need to update the /Users/meyer/Documents/Workspace/Span/presidium-services/web/static/presidium.js file in presidium services.

**Review by Zalaras — APPROVED** [review]

**Pull request merged**
